In [1]:
import sys
import numpy as np

In [3]:
print('Python : {}'.format(sys.version))
print('NumPy : {}'.format(np.__version__))

Python : 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
NumPy : 1.13.3


In [4]:
# defining a scalar
x = 6
x

6

In [6]:
# defining a vector 
x = np.array((1,2,3))
x

array([1, 2, 3])

In [8]:
print('Vector Dimensions : {}'.format(x.shape))
print('Vector size : {}'.format(x.size))

Vector Dimensions : (3,)
Vector size : 3


In [11]:
# defining a matrix
x = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
print('Matrix Dimensions : {}'.format(x.shape))
print('Matrix size : {}'.format(x.size))

Matrix Dimensions : (3, 3)
Matrix size : 9


In [19]:
# define a matrix of a given dimensions
x = np.ones((3,3))
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
print('Matrix Dimensions : {}'.format(x.shape))
print('Matrix size : {}'.format(x.size))

Matrix Dimensions : (3, 3)
Matrix size : 9


In [21]:
# 3 dimensional tensors
x = np.ones((3,3,3))
x

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [22]:
print('Tensor Dimensions : {}'.format(x.shape))
print('Tensor size : {}'.format(x.size))

Tensor Dimensions : (3, 3, 3)
Tensor size : 27


In [24]:
# indexing
A = np.ones((5,5), dtype = np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
A[0,1] = 2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
A[:,0] = 3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [27]:
A[:,:] = 5
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [28]:
# for higher dimensions, simply add an index
A = np.ones((5,5,5), dtype = np.int)

# assign first row a new value
A[:,0,0] = 6
print(A)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [31]:
# matrix operations
A = np.matrix([[1,2], [3,4]])
B = np.ones((2,2), dtype = np.int)

In [32]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [33]:
# Element wise addition
C = A + B 
print(C)

[[2 3]
 [4 5]]


In [34]:
# Element wise subtraction
C = A - B 
print(C)

[[0 1]
 [2 3]]


In [35]:
# Matrix multiplication
C = A*B
print(C)

[[3 3]
 [7 7]]


In [36]:
# the matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
B = A.T
print(B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [38]:
C = B.T
print(C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
A = np.array(range(10))
A = A.reshape(2,5)
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
B = A.T
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [41]:
print(B.shape)

(5, 2)


In [42]:
print(A.shape)

(2, 5)


In [43]:
# tensotrs
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
